name: MiSidetext
version: '1.0-SNAPSHOT'
main: exe.example.miSidetext.MiSidetext
authors: [Example]
description: 一款为Minecraft服务器设计的创意聊天插件，在玩家聊天时显示炫酷的侧边文本效果
api-version: '1.21'
commands:
  misidetext:
    description: 主命令
    aliases: [st]
    usage: /misidetext
permissions:
  misidetext.use:
    description: 允许使用侧边文本功能
    default: true
  misidetext.reload:
    description: 允许重载插件配置
    default: op
  misidetext.settings:
    description: 允许修改动画设置
    default: op
